services:
  postgres:
    image: postgres:16
    container_name: yachtpms_postgres
    environment:
      POSTGRES_USER: yachtpms
      POSTGRES_PASSWORD: yachtpms
      POSTGRES_DB: yachtpms
    ports:
      - "5433:5432"
    volumes:
      - yachtpms_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: yachtpms_redis
    ports:
      - "6379:6379"

volumes:
  yachtpms_pg:
